-- AlterTable
ALTER TABLE "budgets" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'GENERAL',
ADD COLUMN "currentAmount" DECIMAL NOT NULL DEFAULT 0,
ADD COLUMN "percentageUsed" DECIMAL NOT NULL DEFAULT 0,
ADD COLUMN "status" TEXT NOT NULL DEFAULT 'GOOD',
ADD COLUMN "lastChecked" TIMESTAMP(3),
ADD COLUMN "alertCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "userId" DROP NOT NULL;
